const API_URL=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000/api';
const TOKEN_KEY='wanderlust_tokens';
export const tokens={get:()=>{try{return JSON.parse(localStorage.getItem(TOKEN_KEY)||'null')}catch{return null}},set:v=>localStorage.setItem(TOKEN_KEY,JSON.stringify(v)),clear:()=>localStorage.removeItem(TOKEN_KEY)};
async function refresh(){const current=tokens.get();if(!current?.refresh)throw new Error('Authentication required.');const r=await fetch(`${API_URL}/auth/refresh/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh:current.refresh})});if(!r.ok)throw new Error('Your session has expired.');const data=await r.json();tokens.set({...current,...data});return data.access}
export async function api(path,{body,auth=true,...options}={}){let access=tokens.get()?.access;const multipart=body instanceof FormData;const call=async token=>{try{return await fetch(`${API_URL}${path}`,{...options,method:options.method||(body?'POST':'GET'),headers:{...(multipart?{}:{'Content-Type':'application/json'}),...(auth&&token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:multipart?body:JSON.stringify(body)}:{})})}catch{throw new Error('Cannot reach the Wanderlust server. Please check that the backend is running.')}};let response=await call(access);if(response.status===401&&auth&&tokens.get()?.refresh){try{access=await refresh();response=await call(access)}catch{tokens.clear();window.dispatchEvent(new Event('wanderlust:logout'))}}
 if(response.status===401&&auth){tokens.clear();window.dispatchEvent(new Event('wanderlust:logout'))}
 const data=response.status===204?null:await response.json().catch(()=>({detail:'The server returned an invalid response.'}));if(!response.ok){const error=new Error(data?.detail||Object.values(data||{})?.flat()?.[0]||'Request failed.');error.status=response.status;error.data=data;throw error}return data}
export async function login(email,password){const data=await api('/auth/token/',{auth:false,body:{username:email.toLowerCase().trim(),password}});tokens.set(data);const user=await api('/auth/me/');tokens.set({...data,user});return user}
export async function signup(payload){const data=await api('/auth/signup/',{auth:false,body:payload});tokens.set({access:data.access,refresh:data.refresh,user:data.user});return data.user}
