import React,{useMemo,useState} from 'react';
import {useDispatch,useSelector} from 'react-redux';
import {togglePlace,setDays} from './main';
import {MapPin,Search,Heart,Plus,Check,CalendarDays,Compass,Route,Users,MessageCircle,Sparkles,Bell,ChevronRight,Clock,Star,Menu,X,ArrowRight,Map,ShieldCheck,Send} from 'lucide-react';

const places=[
 {id:1,name:'City Palace',city:'Udaipur',cat:'Royal heritage',rating:4.7,distance:'2.5 km',lat:24.5764,lng:73.6835,img:'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=82',desc:'Courtyards, balconies and galleries overlooking the old city.'},
 {id:2,name:'Lake Pichola',city:'Udaipur',cat:'Lake & sunset',rating:4.8,distance:'3.1 km',lat:24.572,lng:73.679,img:'https://images.unsplash.com/photo-1602643163983-ed0babc39797?auto=format&fit=crop&w=1200&q=82',desc:'A serene boat ride framed by palaces and the Aravalli hills.'},
 {id:3,name:'Jagdish Temple',city:'Udaipur',cat:'Living heritage',rating:4.6,distance:'2.1 km',lat:24.5796,lng:73.6837,img:'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=82',desc:'Intricate stone carvings in the heart of the historic quarter.'},
 {id:4,name:'Sajjangarh Palace',city:'Udaipur',cat:'Hilltop viewpoint',rating:4.5,distance:'8.4 km',lat:24.5943,lng:73.6396,img:'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=82',desc:'A dramatic hilltop palace with wide sunset views.'},
 {id:5,name:'Saheliyon ki Bari',city:'Udaipur',cat:'Garden',rating:4.4,distance:'4.2 km',lat:24.6031,lng:73.6856,img:'https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1200&q=82',desc:'Lotus pools, marble pavilions and quiet garden paths.'},
 {id:6,name:'Fateh Sagar Lake',city:'Udaipur',cat:'Nature',rating:4.6,distance:'5.0 km',lat:24.6014,lng:73.6742,img:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=82',desc:'Waterfront promenades, island views and evening breezes.'}
];
const guides=[{name:'Aarav Sharma',role:'Heritage storyteller',rating:4.9,reviews:120,price:'₹2,500',langs:'English · Hindi',initials:'AS'},{name:'Priya Mehta',role:'Food & culture guide',rating:4.8,reviews:89,price:'₹2,000',langs:'English · Hindi · French',initials:'PM'},{name:'Rohit Singh',role:'Adventure specialist',rating:4.7,reviews:76,price:'₹1,800',langs:'English · Hindi',initials:'RS'}];

function Logo(){return <div className="logo"><span className="logoMark">W</span><span>Wanderlust</span></div>}
function Stars({value}){return <span className="rating"><Star size={14} fill="currentColor"/> {value}</span>}
function Header({page,setPage}){const [open,setOpen]=useState(false);return <header><Logo/><nav className={open?'open':''}>{['discover','trips','guides','assistant'].map(x=><button key={x} className={page===x?'active':''} onClick={()=>{setPage(x);setOpen(false)}}>{x==='trips'?'Your Trips':x==='guides'?'Local Guides':x==='assistant'?'AI Assistant':'Discover'}</button>)}</nav><div className="headActions"><button className="icon"><Bell size={20}/><i/></button><div className="avatar">SS</div><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}
function Hero({onSearch}){const [q,setQ]=useState('Udaipur, India');return <section className="hero"><div className="heroShade"/><div className="heroContent"><div className="eyebrow"><Compass size={17}/> Curated journeys, made personal</div><h1>Where will your<br/>next story begin?</h1><p>Discover remarkable places, shape your days, and connect with locals who know every hidden lane.</p><form onSubmit={e=>{e.preventDefault();onSearch(q)}}><MapPin/><input value={q} onChange={e=>setQ(e.target.value)} aria-label="Search a destination"/><button aria-label="Search"><Search/></button></form><div className="chips">{['Beaches','Mountains','Temples','Food','Adventure'].map(x=><button key={x}>{x}</button>)}</div></div><div className="heroNote"><span>Local pick</span><b>Sunset from Ambrai Ghat</b><small>6:25 PM · 23°C</small></div></section>}
function PlaceCard({p}){const dispatch=useDispatch();const selected=useSelector(s=>s.trip.selected.some(x=>x.id===p.id));return <article className="placeCard"><div className="image"><img src={p.img} alt=""/><button className="heart"><Heart size={18}/></button><span>{p.cat}</span></div><div className="placeBody"><div className="placeTitle"><h3>{p.name}</h3><Stars value={p.rating}/></div><p>{p.desc}</p><div className="meta"><MapPin size={14}/>{p.city}<span>•</span>{p.distance}</div><button className={selected?'added':''} onClick={()=>dispatch(togglePlace(p))}>{selected?<><Check/> Added</>:<><Plus/> Add to trip</>}</button></div></article>}
function Selection(){const selected=useSelector(s=>s.trip.selected),days=useSelector(s=>s.trip.days),dispatch=useDispatch();return <aside className="selection"><div className="selectionHead"><div><span className="step">TRIP BUILDER</span><h2>Plan your escape</h2></div><span className="count">{selected.length}</span></div><label>Destination<div className="input"><MapPin/>Udaipur, India</div></label><div className="dateRow"><label>Start<input type="date" defaultValue="2026-10-10"/></label><label>Days<select value={days} onChange={e=>dispatch(setDays(+e.target.value))}>{[2,3,4,5,6,7].map(n=><option key={n}>{n}</option>)}</select></label></div><div className="selectedList"><div className="listTitle"><b>Selected places</b><span>{selected.length?`${selected.length} ready`:'Choose from the list'}</span></div>{selected.length===0?<div className="empty"><Route/><p>Add places to build a route that feels unhurried.</p></div>:selected.map((p,i)=><div className="selectedItem" key={p.id}><span>{i+1}</span><img src={p.img}/><div><b>{p.name}</b><small>{p.cat}</small></div><button onClick={()=>dispatch(togglePlace(p))}><X/></button></div>)}</div><button className="primary" disabled={!selected.length} onClick={()=>document.getElementById('itinerary')?.scrollIntoView({behavior:'smooth'})}><Sparkles/> Generate {days}-day trip</button><small className="privacy"><ShieldCheck/> Your plan stays private until you share it.</small></aside>}
function Discover(){const [searched,setSearched]=useState(false);return <><Hero onSearch={()=>setSearched(true)}/><main><div className="content"><div className="sectionTop"><div><span className="kicker">{searched?'SEARCH RESULTS':'HANDPICKED FOR YOU'}</span><h2>Places worth your time</h2><p>Independent discoveries, iconic landmarks, and local favourites.</p></div><button className="mapButton"><Map/> Map view</button></div><div className="places">{places.map(p=><PlaceCard key={p.id} p={p}/>)}</div></div><Selection/></main><Itinerary/></>}
function Itinerary(){const selected=useSelector(s=>s.trip.selected),days=useSelector(s=>s.trip.days);const items=selected.length?selected:places.slice(0,4);return <section id="itinerary" className="itinerary"><div className="itHead"><div><span className="kicker">YOUR ROUTE</span><h2>{days} days in Udaipur</h2><p>Grouped by proximity, with breathing room built in.</p></div><button className="outline"><Route/> Optimize route</button><button className="primary compact">Save trip</button></div><div className="planner"><div className="timeline"><div className="dayTabs">{Array.from({length:days},(_,i)=><button className={i===0?'active':''} key={i}>Day {i+1}<small>Oct {10+i}</small></button>)}</div><h3>Day 1 · The old city & lakeside</h3>{items.slice(0,4).map((p,i)=><div className="stop" key={p.id}><div className="stopNo">{i+1}</div><img src={p.img}/><div><b>{p.name}</b><span><Clock/> {9+i*2}:00 AM · {p.distance}</span><small>{i===2?'Lunch nearby · 60 min':'Suggested visit · 90 min'}</small></div><button>•••</button></div>)}<button className="addStop"><Plus/> Add a place</button></div><div className="map"><div className="mapGrid"/>{items.slice(0,4).map((p,i)=><div className={`marker m${i+1}`} key={p.id}>{i+1}</div>)}<svg viewBox="0 0 600 420" preserveAspectRatio="none"><path d="M145 305 C180 250 210 260 245 205 S350 115 410 155 S470 250 520 100"/></svg><div className="mapCard"><MapPin/><div><b>Route preview</b><small>14.2 km · about 52 min travel</small></div></div></div></div></section>}
function Trips(){return <div className="page"><div className="pageTitle"><div><span className="kicker">YOUR JOURNEYS</span><h1>Trips you’re shaping</h1><p>Everything saved, upcoming and remembered.</p></div><button className="primary compact"><Plus/> Create trip</button></div><div className="tabs"><button className="active">Upcoming <span>2</span></button><button>Saved <span>1</span></button><button>Past <span>3</span></button></div><div className="tripGrid">{[{title:'Udaipur, unhurried',date:'Oct 10–14, 2026',img:places[0].img,meta:'4 days · 6 places · Guide requested'},{title:'Kerala backwaters',date:'Jan 18–23, 2027',img:'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=82',meta:'6 days · 9 places · Self-guided'},{title:'Bali coast & temples',date:'Saved for later',img:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=82',meta:'7 days · 11 places'}].map(t=><article className="tripCard" key={t.title}><img src={t.img}/><div><span>{t.date}</span><h3>{t.title}</h3><p>{t.meta}</p><button>Open trip <ArrowRight/></button></div></article>)}</div></div>}
function Guides(){return <div className="page"><div className="guideHero"><div><span className="kicker">LOCAL PERSPECTIVE</span><h1>Meet Udaipur beyond the guidebook</h1><p>Choose a verified local whose interests, pace, and availability match your trip.</p></div></div><div className="filterbar"><div><CalendarDays/> Oct 10–14, 2026</div><div>Any language</div><div>Any specialty</div><button>Filters</button></div><div className="guideList">{guides.map((g,i)=><article className="guide" key={g.name}><div className={`portrait p${i}`}>{g.initials}</div><div className="guideInfo"><div><h3>{g.name}</h3><Stars value={g.rating}/><span className="reviewCount">({g.reviews} reviews)</span></div><b>{g.role}</b><p>{g.langs} · Udaipur city & old quarter</p><div className="tags"><span>Heritage</span><span>Hidden gems</span><span>{i===1?'Negotiable':'Fixed price'}</span></div></div><div className="guidePrice"><b>{g.price}<small>/day</small></b><span className="available">Available</span><button>View profile</button><button className="primary compact">Request guide</button></div></article>)}</div></div>}
function Assistant(){const [messages,setMessages]=useState([{from:'ai',text:'I know the shape of your Udaipur trip. Ask about pacing, food, local customs, or ideas near your current stops.'}]);const [text,setText]=useState('');function send(e){e.preventDefault();if(!text.trim())return;setMessages([...messages,{from:'me',text},{from:'ai',text:'Day 1 is nicely grouped around the old city. For the evening, consider a lakeside walk at Ambrai Ghat after City Palace. I’ll never change your itinerary without asking.'}]);setText('')}return <div className="assistantPage"><aside><Logo/><button className="newChat"><Plus/> New conversation</button><b>Current trip</b><div className="context"><MapPin/><div><strong>Udaipur, unhurried</strong><span>Oct 10–14 · 6 places</span></div></div><b>Try asking</b>{['Is Day 1 too busy?','Where should we eat?','Suggest an evening plan','What should I book early?'].map(x=><button className="suggestion" key={x} onClick={()=>setText(x)}>{x}<ChevronRight/></button>)}</aside><section className="chat"><div className="chatHead"><div className="aiIcon"><Sparkles/></div><div><b>Travel Assistant</b><span>Using your current trip context</span></div><i>Online</i></div><div className="messages">{messages.map((m,i)=><div className={`message ${m.from}`} key={i}>{m.text}</div>)}</div><form onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about your trip…"/><button><Send/></button></form><small>Suggestions are guidance. Places are validated before you can add them.</small></section></div>}
function App(){const [page,setPage]=useState('discover');return <div><Header page={page} setPage={setPage}/>{page==='discover'?<Discover/>:page==='trips'?<Trips/>:page==='guides'?<Guides/>:<Assistant/>}<footer><Logo/><span>Thoughtful trips. Real local knowledge.</span><span>© 2026 Wanderlust</span></footer></div>}
export default App;
