import React,{useEffect,useState} from 'react';
import {Link,useLocation,useSearchParams} from 'react-router-dom';
import {api} from './api';
import {Sparkles,X,Send} from 'lucide-react';
import {useDispatch} from 'react-redux';
import {setUser} from './main';

const list=data=>data?.results||data||[];
export function Notifications(){
 const [items,setItems]=useState([]),[error,setError]=useState('');
 const reload=()=>api('/notifications/').then(data=>setItems(list(data))).catch(exc=>setError(exc.message));
 useEffect(()=>{reload()},[]);
 async function read(id){try{await api(`/notifications/${id}/read/`,{body:{}});reload()}catch(exc){setError(exc.message)}}
 return <div className="page"><div className="pageTitle"><div><span className="kicker">ACTIVITY</span><h1>Notifications</h1></div></div>{error&&<div className="formError">{error}</div>}{!items.length&&<p>Nothing new yet.</p>}{items.map(item=><div className="panelRow" key={item.id}><b>{item.title}</b><span>{item.body} · {new Date(item.created_at).toLocaleString()}</span>{!item.read_at&&<button onClick={()=>read(item.id)}>Mark read</button>}</div>)}</div>
}

export function ProfilePhoto({user,onUploaded}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function upload(event){const file=event.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('photo',file);const updated=await api('/auth/photo/',{body:form});onUploaded(updated)}catch(exc){setError(exc.message)}finally{setBusy(false)}}return <div className="profilePhotoBox"><div className="profilePortrait">{user?.photo_url?<img src={user.photo_url} alt="Your profile"/>:user?.name?.slice(0,1)}</div><div><b>Profile photo</b><p>Choose a JPG, PNG or WebP image under 5 MB.</p><label className="outline photoUpload">{busy?'Uploading…':'Upload photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={busy}/></label>{error&&<small className="formError">{error}</small>}</div></div>}

export function TouristProfile(){
 const dispatch=useDispatch(),[data,setData]=useState(null),[form,setForm]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/auth/profile/').then(result=>{setData(result);setForm({first_name:result.user.first_name||'',last_name:result.user.last_name||'',phone:result.user.phone||'',bio:result.tourist.bio||'',home_city:result.tourist.home_city||'',travel_style:result.tourist.travel_style||'',interests:(result.tourist.interests||[]).join(', ')})}).catch(exc=>setError(exc.message))},[]);
 async function save(event){event.preventDefault();setBusy(true);setError('');try{const updated=await api('/auth/profile/',{method:'PATCH',body:{...form,interests:form.interests.split(',').map(x=>x.trim()).filter(Boolean)}});setData(updated);dispatch(setUser(updated.user));setMessage('Profile saved.')}catch(exc){setError(exc.message)}finally{setBusy(false)}}
 function uploaded(user){setData(current=>({...current,user}));dispatch(setUser(user));setMessage('Photo uploaded.')}
 return <div className="page profilePage"><div className="pageTitle"><div><span className="kicker">YOUR ACCOUNT</span><h1>Your traveller profile</h1><p>Show guides who you are and what you love to explore.</p></div></div>{error&&<div className="formError">{error}</div>}{data&&form?<div className="profileLayout"><section className="formPanel profileIntro"><ProfilePhoto user={data.user} onUploaded={uploaded}/><h2>{data.user.name}</h2><p>{data.user.email}</p><span className="profileRole">Tourist account</span></section><form className="formPanel profileFields" onSubmit={save}><h2>About you</h2><div className="profileTwoCols"><label>First name<input value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})} required/></label><label>Last name<input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label></div><div className="profileTwoCols"><label>Email<input value={data.user.email} disabled/></label><label>Phone<input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Optional"/></label></div><label>Home city<input value={form.home_city} onChange={e=>setForm({...form,home_city:e.target.value})} placeholder="Where are you based?"/></label><label>About me<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} placeholder="Tell local guides a little about yourself"/></label><label>Travel style<input value={form.travel_style} onChange={e=>setForm({...form,travel_style:e.target.value})} placeholder="Culture, food, adventure…"/></label><label>Interests (comma-separated)<input value={form.interests} onChange={e=>setForm({...form,interests:e.target.value})} placeholder="Heritage, nature, cuisine"/></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save profile'}</button>{message&&<p className="statusLine">{message}</p>}</form></div>:!error&&<p>Loading profile…</p>}</div>
}

export function TouristBookings(){
 const [bookings,setBookings]=useState([]),[requests,setRequests]=useState([]),[reviews,setReviews]=useState([]),[error,setError]=useState(''),[rating,setRating]=useState(5),[text,setText]=useState('');
 async function reload(){try{const [bookingData,requestData,reviewData]=await Promise.all([api('/bookings/'),api('/requests/'),api('/reviews/')]);setBookings(list(bookingData));setRequests(list(requestData));setReviews(list(reviewData))}catch(exc){setError(exc.message)}}
 useEffect(()=>{reload()},[]);
 async function cancel(id){if(!window.confirm('Cancel this booking?'))return;try{await api(`/bookings/${id}/change_status/`,{body:{status:'CANCELLED'}});reload()}catch(exc){setError(exc.message)}}
 async function cancelRequest(id){if(!window.confirm('Cancel this guide request?'))return;try{await api(`/requests/${id}/transition/`,{body:{status:'CANCELLED'}});reload()}catch(exc){setError(exc.message)}}
 async function review(event,id){event.preventDefault();try{await api('/reviews/',{body:{booking:id,rating:Number(rating),text}});setText('');reload()}catch(exc){setError(exc.message)}}
 return <div className="page"><div className="pageTitle"><div><span className="kicker">LOCAL TOURS</span><h1>Requests & bookings</h1><p>Track every step from your first message to a confirmed tour.</p></div></div>{error&&<div className="formError">{error}</div>}<h2>Guide requests</h2>{!requests.length&&<p>No guide requests yet. <Link to="/guides">Find a local guide</Link>.</p>}{requests.map(item=><div className="formPanel bookingCard" key={item.id}><div><h3>{item.guide_name} · {item.service_title}</h3><p>{new Date(item.start).toLocaleString()} → {new Date(item.end).toLocaleString()} · {item.people} people</p><b className="statusLine">{item.status}</b></div><div className="buttonRow"><Link to={`/messages?request=${item.id}`}>Message guide</Link>{['PENDING','NEGOTIATING','ACCEPTED'].includes(item.status)&&<button onClick={()=>cancelRequest(item.id)}>Cancel request</button>}</div></div>)}<h2>Confirmed bookings</h2>{!bookings.length&&<p>No confirmed bookings yet. A guide confirms an accepted request.</p>}{bookings.map(booking=>{const existing=reviews.find(item=>item.booking===booking.id);return <div className="formPanel bookingCard" key={booking.id}><h3>Booking #{booking.id}</h3><p>{new Date(booking.start).toLocaleString()} → {new Date(booking.end).toLocaleString()} · ₹{booking.final_price} · {booking.status}</p>{booking.status==='CONFIRMED'&&<button className="outline" onClick={()=>cancel(booking.id)}>Cancel booking</button>}{booking.status==='COMPLETED'&&!existing&&<form onSubmit={event=>review(event,booking.id)}><label>Rating<select value={rating} onChange={event=>setRating(event.target.value)}>{[5,4,3,2,1].map(number=><option key={number}>{number}</option>)}</select></label><label>Your review<textarea value={text} onChange={event=>setText(event.target.value)}/></label><button className="primary">Submit review</button></form>}{existing&&<p>Your review: {existing.rating}/5 — {existing.text}</p>}</div>})}</div>
}

export function GuideReviews(){
 const [items,setItems]=useState([]),[error,setError]=useState('');
 useEffect(()=>{api('/reviews/').then(data=>setItems(list(data))).catch(exc=>setError(exc.message))},[]);
 return <div className="page"><div className="pageTitle"><div><span className="kicker">TRAVELLER FEEDBACK</span><h1>Your reviews</h1></div></div>{error&&<div className="formError">{error}</div>}{!items.length&&<p>No completed-tour reviews yet.</p>}{items.map(item=><div className="panelRow" key={item.id}><b>{item.rating}/5</b><span>{item.text} · {new Date(item.created_at).toLocaleDateString()}</span></div>)}</div>
}

export function Assistant(){
 const [query]=useSearchParams(),[trip,setTrip]=useState(null),[messages,setMessages]=useState([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const id=query.get('trip');if(id)api(`/trips/${id}/`).then(setTrip).catch(exc=>setError(exc.message))},[query]);
 async function ask(event){event.preventDefault();setBusy(true);setError('');try{const result=await api('/assistant/ask/',{body:{question,trip_id:trip?.id}});setMessages(previous=>[...previous,{q:question,a:result.answer}]);setQuestion('')}catch(exc){setError(exc.message)}finally{setBusy(false)}}
 return <div className="page"><div className="pageTitle"><div><span className="kicker">TRAVEL GUIDANCE</span><h1>AI Travel Assistant</h1><p>{trip?`Discussing ${trip.title} · ${trip.days.length} days`:'Ask about a destination or open a trip for itinerary context.'}</p></div></div>{error&&<div className="formError">{error}</div>}<div className="formPanel assistantPanel"><div className="messageThread">{messages.map((message,index)=><React.Fragment key={index}><div className="bubble mine">{message.q}</div><div className="bubble">{message.a}</div></React.Fragment>)}{!messages.length&&<p>Ask about food, places, local customs, or your current itinerary.</p>}</div><form className="inlineForm" onSubmit={ask}><input value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Ask about your trip…" required/><button disabled={busy}>Ask</button></form></div></div>
}

export function AssistantWidget(){
 const location=useLocation(),[open,setOpen]=useState(false),[question,setQuestion]=useState(''),[messages,setMessages]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const tripId=location.pathname.match(/^\/trips\/(\d+)$/)?.[1];
 async function ask(event){event.preventDefault();if(!question.trim())return;const current=question.trim();setBusy(true);setError('');try{const response=await api('/assistant/ask/',{body:{question:current,...(tripId?{trip_id:Number(tripId)}:{})}});setMessages(items=>[...items,{q:current,a:response.answer}]);setQuestion('')}catch(exc){setError(exc.message)}finally{setBusy(false)}}
 return <div className="assistantDock"><button className="assistantLauncher" onClick={()=>setOpen(!open)} aria-label={open?'Close travel assistant':'Open travel assistant'}>{open?<X/>:<Sparkles/>}<span>{open?'Close':'Ask Wanderlust'}</span></button>{open&&<section className="assistantWidget"><div className="assistantWidgetHead"><div><b>AI Travel Assistant</b><small>{tripId?'Here to help with this trip':'Available throughout Wanderlust'}</small></div><button onClick={()=>setOpen(false)} aria-label="Close"><X size={18}/></button></div><div className="assistantWidgetMessages">{messages.length?messages.map((m,i)=><React.Fragment key={i}><div className="bubble mine">{m.q}</div><div className="bubble">{m.a}</div></React.Fragment>):<p>Ask about a place, your itinerary, or guiding travellers.</p>}{error&&<div className="formError">{error}</div>}</div><form onSubmit={ask}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask anything about travel…" required/><button disabled={busy} aria-label="Send question"><Send size={17}/></button></form></section>}</div>
}
