import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from './api';
import {MapPin,Star,Search,X} from 'lucide-react';

const list=data=>data?.results||data||[];
export default function GuidesMarketplace(){
 const [guides,setGuides]=useState([]),[trips,setTrips]=useState([]),[destination,setDestination]=useState(''),[city,setCity]=useState(''),[date,setDate]=useState(''),[from,setFrom]=useState(''),[until,setUntil]=useState(''),[selected,setSelected]=useState(null),[requestOpen,setRequestOpen]=useState(false),[slots,setSlots]=useState(null),[trip,setTrip]=useState(''),[service,setService]=useState(''),[people,setPeople]=useState(1),[note,setNote]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{api('/trips/').then(d=>setTrips(list(d))).catch(e=>setMessage(e.message))},[]);
 useEffect(()=>{loadGuides()},[destination,date,from,until]);
 async function loadGuides(){setLoading(true);setMessage('');try{const params=new URLSearchParams();if(destination)params.set('destination',destination);if(date&&from&&until){params.set('date',date);params.set('start',new Date(`${date}T${from}`).toISOString());params.set('end',new Date(`${date}T${until}`).toISOString())}setGuides(list(await api(`/guides/?${params}`)))}catch(e){setMessage(e.message)}finally{setLoading(false)}}
 async function findCity(e){e.preventDefault();try{const result=await api(`/destinations/search/?q=${encodeURIComponent(city)}`);setDestination(String(result.id));setMessage(`Showing guides covering ${result.name}.`)}catch(e){setMessage(e.message)}}
 useEffect(()=>{if(selected&&date)api(`/guide-account/slots/?guide=${selected.id}&date=${date}`).then(setSlots).catch(()=>setSlots(null));else setSlots(null)},[selected,date]);
 const availableTrips=selected?trips.filter(t=>selected.coverage.some(c=>c.destination===t.destination)&&(!date||(t.start_date<=date&&date<=t.end_date))):trips;
 const chosenTrip=trips.find(t=>String(t.id)===String(trip));
 const requestServices=selected?.services.filter(s=>s.active&&(!chosenTrip||selected.coverage.some(c=>c.id===s.coverage&&c.destination===chosenTrip.destination)))||[];
 useEffect(()=>{if(requestServices.length&&!requestServices.some(s=>String(s.id)===String(service)))setService(requestServices[0].id)},[trip,selected]);
 function openRequest(guide){setSelected(guide);setRequestOpen(true);setService(guide.services.find(s=>s.active)?.id||'');setTrip('auto');setNote('');setMessage('')}
 function chooseSlot(slot){const start=new Date(slot.start),duration=selected.services.find(s=>String(s.id)===String(service))?.duration_minutes||120,end=new Date(start.getTime()+duration*60000);setFrom(`${String(start.getHours()).padStart(2,'0')}:${String(start.getMinutes()).padStart(2,'0')}`);setUntil(`${String(end.getHours()).padStart(2,'0')}:${String(end.getMinutes()).padStart(2,'0')}`)}
 async function sendRequest(e){e.preventDefault();setMessage('');try{if(!date||!from||!until)throw new Error('Choose a tour date and time.');const start=new Date(`${date}T${from}`),end=new Date(`${date}T${until}`);if(!(end>start))throw new Error('End time must be later than start time.');const payload={guide:selected.id,service:Number(service),start:start.toISOString(),end:end.toISOString(),people:Number(people),message:note};if(trip!=='auto')payload.trip=Number(trip);const result=await api('/requests/',{body:payload});setMessage(`Request #${result.id} sent. Open Messages to chat with your guide.`);setSelected(null);setRequestOpen(false)}catch(err){setMessage(err.message)}}
 return <div className="page"><div className="guideHero"><div><span className="kicker">LOCAL PERSPECTIVE</span><h1>Meet people who know the place</h1><p>Find a guide whose services cover your trip and who is available when you need them.</p></div></div>
  <div className="guideFilters"><form onSubmit={findCity} className="inlineForm"><input aria-label="Search city" value={city} onChange={e=>setCity(e.target.value)} placeholder="Search a city…" required/><button><Search/> Find</button></form><label>Or choose a trip destination<select value={destination} onChange={e=>setDestination(e.target.value)}><option value="">All destinations</option>{trips.map(t=><option key={t.id} value={t.destination}>{t.destination_detail?.name}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>From<input type="time" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Until<input type="time" value={until} onChange={e=>setUntil(e.target.value)}/></label></div>
  {message&&!selected&&<div className="statusLine">{message}</div>}{loading&&<p>Finding guides…</p>}{!loading&&!guides.length&&<div className="state">No guides match these filters yet. Try another date or destination.</div>}
  <div className="guideList">{guides.map(g=><article className="guide" key={g.id}>{g.photo_url?<img className="guidePhoto" src={g.photo_url} alt={g.name}/>:<div className="portrait">{g.name.split(' ').map(part=>part[0]).slice(0,2).join('')}</div>}<div className="guideInfo"><h3>{g.name}</h3><span className="reviewCount"><Star/> {g.rating?Number(g.rating).toFixed(1):'New'} · {g.review_count} reviews</span><b>{g.years_experience} years experience</b><p>{g.bio||'Local guide building their Wanderlust profile.'}</p><p>{(g.languages||[]).join(' · ')||'Languages not listed'}</p><div className="tags">{(g.specialties||[]).map(x=><span key={x}>{x}</span>)}</div><p><MapPin/> {g.coverage.map(c=>c.label).join(', ')||'Coverage not added'}</p></div><div className="guidePrice"><span className={g.accepting_bookings?'available':'unavailable'}>{g.accepting_bookings?'Accepting bookings':'Unavailable'}</span><b>{g.services.some(s=>s.active)?`From ₹${Math.min(...g.services.filter(s=>s.active).map(s=>Number(s.price)))}`:'No active service'}</b><button onClick={()=>{setSelected(g);setRequestOpen(false);setMessage('')}}>View profile</button><button className="primary" disabled={!g.accepting_bookings||!g.services.some(s=>s.active)} onClick={()=>openRequest(g)}>Request guide</button></div></article>)}</div>
  {selected&&<div className="modalBackdrop" onClick={()=>setSelected(null)}><div className="formPanel requestModal" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><h2>{selected.name}</h2><p>{selected.bio||'Local guide'}</p><p>{selected.languages.join(' · ')} · {selected.years_experience} years experience</p><h3>Services</h3>{selected.services.filter(s=>s.active).map(s=><div className="panelRow" key={s.id}><b>{s.title} · ₹{s.price}</b><span>{s.description} · {s.duration_minutes} min · max {s.max_group_size} people</span></div>)}
   {message&&<div className="formError">{message}</div>}
   {requestOpen?<form onSubmit={sendRequest}><label>Service<select value={service} onChange={e=>setService(e.target.value)} required>{requestServices.map(s=><option key={s.id} value={s.id}>{s.title} · ₹{s.price}</option>)}</select></label><label>Trip<select value={trip} onChange={e=>setTrip(e.target.value)}><option value="auto">New day trip for this booking</option>{availableTrips.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><div className="profileTwoCols"><label>Tour date<input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Group size<input type="number" min="1" max={selected.services.find(s=>String(s.id)===String(service))?.max_group_size||1} value={people} onChange={e=>setPeople(e.target.value)} required/></label></div>{slots&&<div className="availableSlots"><b>Available windows</b>{slots.slots.length?slots.slots.map((s,i)=><button key={i} type="button" onClick={()=>chooseSlot(s)}>{new Date(s.start).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} – {new Date(s.end).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</button>):<p>No availability on this date. Choose another day.</p>}</div>}<div className="profileTwoCols"><label>From<input type="time" value={from} onChange={e=>setFrom(e.target.value)} required/></label><label>Until<input type="time" value={until} onChange={e=>setUntil(e.target.value)} required/></label></div><label>Message to guide<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Tell your guide what you would like to do"/></label><button className="primary" disabled={!requestServices.length}>Send guide request</button><p className="bookingHint">Your guide accepts and confirms the request before it becomes a booking.</p></form>:<button className="primary" disabled={!selected.accepting_bookings||!selected.services.some(s=>s.active)} onClick={()=>{setRequestOpen(true);setTrip('auto')}}>Request this guide</button>}</div></div>}</div>
}
