# Generated by Django 5.2.17 on 2026-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='specialties',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
