# Generated by Django 5.2.17 on 2026-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guideprofile_onboarding_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
