# Generated by Django 5.2.17 on 2026-09-24 01:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_guideprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='home_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='interests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='travel_style',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to=core.models.profile_photo_path),
        ),
    ]
