# Generated by Django 5.2.17 on 2026-09-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_destination_image_url_touristprofile_home_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='places_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
